# Generated by Django 4.0.5 on 2022-09-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registerstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudents',
            name='archive',
            field=models.FileField(max_length=255, upload_to=None),
        ),
    ]
