# Generated by Django 4.0.5 on 2022-09-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_registerstudents_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='matriculation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
