# Generated by Django 4.0.5 on 2022-09-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_matriculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='nickname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
