# Generated by Django 4.0.5 on 2022-10-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_photouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='photo',
        ),
    ]
