# Generated by Django 4.0.5 on 2022-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useraccount_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
