# Generated by Django 4.0.5 on 2023-01-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useraccount_score_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
