# Generated by Django 4.0.5 on 2023-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_score_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='acert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='tried',
            field=models.BooleanField(default=False),
        ),
    ]
