# Generated by Django 4.0.5 on 2022-12-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamment.group'),
        ),
    ]
