# Generated by Django 4.0.5 on 2022-12-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamment', '0002_alter_members_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='online',
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
    ]
