# Generated by Django 4.0.5 on 2022-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamment', '0003_members_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='boss',
            field=models.BooleanField(default=False),
        ),
    ]
