# Generated by Django 4.0.5 on 2022-12-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamment', '0005_alter_members_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
