# Generated by Django 4.0.5 on 2022-12-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamment', '0007_alter_members_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamment.group'),
        ),
    ]
