# Generated by Django 4.0.5 on 2022-10-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='disicplina',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='teste',
        ),
    ]
