# Generated by Django 4.0.5 on 2022-10-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_ask_disicplina_remove_ask_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='nameAuthor',
        ),
    ]
