# Generated by Django 4.0.5 on 2023-01-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_configrate_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configrate',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
