# Generated by Django 4.0.5 on 2023-01-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_configrate_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configrate',
            name='rate_challenges',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='configrate',
            name='rate_exercise',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='configrate',
            name='rate_games',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='configrate',
            name='rate_tournamment',
            field=models.FloatField(default=0.25),
        ),
    ]
