# Generated by Django 4.0.5 on 2022-10-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-availability',),
            },
        ),
        migrations.CreateModel(
            name='ListExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-availability',),
            },
        ),
        migrations.CreateModel(
            name='QuestionChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('result', models.TextField()),
                ('data_created', models.DateField(auto_now=True)),
                ('resolution', models.TextField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.listchallenge')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('result', models.TextField()),
                ('data_created', models.DateField(auto_now=True)),
                ('resolution', models.TextField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.listexercise')),
            ],
        ),
    ]
