# Generated by Django 4.0.5 on 2022-09-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('result', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('data_created', models.DateField(auto_now=True)),
                ('resolution', models.TextField()),
            ],
        ),
    ]
