# Generated by Django 4.0.5 on 2022-10-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_listchallenge_questionchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchallenge',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.listchallenge'),
        ),
    ]
