# Generated by Django 4.0.5 on 2022-09-23 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('text', ckeditor.fields.RichTextField()),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
