# Generated by Django 4.0.5 on 2022-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.FileField(blank=True, default='content/content.svg', upload_to='content'),
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
